### ISSUE TITLE
Include an admin-user function defintion in docs

### ISSUE THREAD

**Issue by deadghost** [funcool/buddy-auth#15]
In `6.2. Rules Handlers` portion of the docs, an undefined function `admin-user` is used. It wasn't immediately clear to me how I could define such a function for my own use and an example would be very helpful.

**Comment by niwinz** [comment]
I have not included it because the implementations of that can be very heterogeneous and I don't want condition the people. it is not enough cleat that is a hypothetical function for admin checking ?

**Comment by deadghost** [comment]
I generally don't like hypothetical functions in documentation because when I'm unsure what it is supposed to do, I immediately scroll back to try to find the definition. It's not necessarily bad, but I think it's certainly a documentation smell where we can suspect something could have been explained better.

The missing function in question is found in `6.2. Rules Handlers`. I think the true issue is that I would like to know how to write a rule handler but there are gaps in the documentation showing how to do so.

As for implementations being heterogeneous, I'm not sure what the problem with that is. If the written examples work and are of good, idiomatic quality, who cares if they copy paste the code and adapt it to their purposes?

I don't think I have ever complained about something having too much documentation or too many examples.

**Comment by niwinz** [comment]
I have thought about this, and I understand your arguments, but define all hypothetical rule handlers used in examples is not assumible. The concrete example is the `admin-user` it can be defined in 100 different ways and some one will need a database access for check if a user is "admin". That is completely out of scope. Providing a simple dummy example definition is completely useless in my opinion.

The documentation comes with an example of the aspect of one rule handler, this can be extrapolated  to all hypothetical examples. I have added in some parts the note that that in the the examples are hypothetically defined rule handlers.

In any case, thanks for your suggestion. I appreciate much that!
