### ISSUE TITLE
Group Access Rules under Authorization in docs

### ISSUE THREAD

**Issue by deadghost** [funcool/buddy-auth#16]
Since section `6. Access Rules` is part of the authorization process, perhaps it should be a subsection of `5. Authorization`.

**Comment by niwinz** [comment]
Yeah, maybe you are right. In previous doc versions, I have the access rules behind the authorization but as access rules is a big entity in some time I have split them in two sections.

If I'll put access rules behind authorization again, I think that access rulles will be more hidden... something that I don't want :S

**Comment by niwinz** [comment]
Already done, I will push it in some time to the repository.
