### ISSUE TITLE
Multiple backends

### ISSUE THREAD

**Issue by r0man** [funcool/buddy-auth#21]
I would like to use multiple backends. Would you take a PR that extends `wrap-authentication` to work with multiple backends? Like this:

```
(wrap-authentication http-basic-backend jws-backend)
```

The idea is to try all passed backends in order. If one of them succeeds call the handler, otherwise return the failure response of the last backend?

Roman

**Comment by niwinz** [comment]
Yes! Is really a great idea!

**Comment by r0man** [comment]
Ok, cool. I'll prepare something tomorrow ...

**Comment by niwinz** [comment]
Would be great. I think that today I will finish all the necessary work on JWE on buddy-sign and tomorrow I have plans for implement JWE auth backend in buddy-auth and merege the your upcoming PR and release a new version ;)

**Comment by niwinz** [comment]
Fixed by #22
