### ISSUE TITLE
Broken tokens should raise an error resulting in 401, not 500

### ISSUE THREAD

**Issue by lvh** [funcool/buddy-auth#24]
For example, I wrote a test:

``` clojure
(testing "authenticated access with bad credentials"
    (d/let-flow
     [r (api/handler (-> (mock/request :post "/authenticate")
                         (mock/header "Authorization" "Token xyzzy")))]
     (is (= (:status r) 401))))
```

However, instead I get a 500 with a weird random exception:

```
Error in handler-test
Uncaught exception, not in assertion.
expected: nil
  actual: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('�' (code 65533 / 0xfffd)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@5ccb2c27; line: 1, column: 2]
```

**Comment by niwinz** [comment]
You are right, I will fix it!

**Comment by lvh** [comment]
Awesome! thanks in advance :)

**Comment by niwinz** [comment]
I'm not pretty sure that 401 is a proper response. If provided token is wrong, is how no token is available, so the return 401 or 403 is not the responsability of authrozation layer, the authentication layer should only authenticate if it can do it or do nothing  as default behavior.

If not authenticated request with wrong token passes down  to your ring handler and the ring handler has a proper autorization control, that will result in a proper 401 response from the authorization layer.

In any case, that are only my thinking! I will fix it this afternoon and release a bugfix version.

**Comment by niwinz** [comment]
Now is already fixed, and new version is released of buddy-sign, buddy-auth (and buddy metapackage).

**Comment by lvh** [comment]
Yeah; you're right. It shouldn't really be 401, but maybe 400 or something. At the very least it should be 4xx and not 5xx :) Thank you for fixing this so quickly!

**Comment by niwinz** [comment]
Thanks to you for report that bug \o/
