### ISSUE TITLE
Improve documentation about how use jwe and link to the buddy-sign documentation for detailed JWE doc.

### ISSUE THREAD

**Issue by upgradingdave** [funcool/buddy-auth#25]
I'm really enjoying using buddy-auth. Thanks much for this work!

I have a question about JWE (and this is probably more about JWE than buddy-auth, but hoping someone here might be able to shed some light). 

The JWS and JWE examples are great, thanks for providing those. 

The way I understand using JWS: 2 programs know a shared secret. One program uses shared secret to sign, and the other program uses the same secret to validate signature. If I understand that correctly, then that makes sense. 

But I'm a little confused about how to take the JWE example and use it in the real world. If the program that encrypts the payload creates the nonce, then how to share that nonce with the program that needs to decrypt the payload? 

Thanks for your help, 
Dave

**Comment by upgradingdave** [comment]
Ok, I see now (in the tests) that you can use a sha256 encrypted secret and share that between 2 parties to use for encryption/decryption of jwe. 

Is it possible to use public/private keys for jwe? If so, if someone wouldn't mind posting an example, that'd be awesome. Thanks!

**Comment by niwinz** [comment]
You are right! The current documentation in buddy-auth package is slightly limited. I will update it for the next version.

Some additional information you can found about JWE/JWS support on the buddy-sign module https://funcool.github.io/buddy-sign/latest/#_json_web_encryption, but that also do not explain how use asymetric key pairs (aka RSA). I will update documentation for the next version sure!

In any case, use asimetric keys is very easy, just read your keys with functions exposed in buddy-core
https://funcool.github.io/buddy-core/latest/#_public_private_keypairs and pass them as sectret parameter on the jwe functions (and not forget select proper key encryption algorithm)

**Comment by upgradingdave** [comment]
I hadn't seen that documentation yet, thanks for those links and thanks even more for the great documentation. The clojure community never ceases to amaze. And your buddy libs just set the bar even higher!

**Comment by niwinz** [comment]
Is already done.
