### ISSUE TITLE
Access Rules: re-matches on path-info breaks pattern matching

### ISSUE THREAD

**Issue by rwilson** [funcool/buddy-auth#28]
Discovered when trying to use buddy-auth access rules in a project with compojure route definitions that use compojure's `context`. I haven't tested to see whether it's specific to compojure or whether it occurs without compojure or without the use of the `context` fn.

The crux of the problem is the compiled `:pattern` matcher, specifically that it matches against `:path-info` if it exists, rather than always using the `:uri`. Here's the relevant code:

``` clojure
;; rwilson- Excerpt from buddy.auth.accessrules/compile-access-rule, with comments added
(fn [request]
  (let [pattern (:pattern accessrule)
        ;; rwilson- the inclusion of :path-info here breaks the ability to match the
        ;;          whole uri, which is problematic because :path-info can be non-nil
        ;;          and also irrelevant to the matching, as demonstrated below.
        uri (or (:path-info request)
                 (:uri request))]
    (when (and (matches-request-method request request-method)
               (seq (re-matches pattern uri)))
      {})))
```

Here's an example. Given the following:

``` clojure
(defroutes routes
  (context "/account/:account-id[a-zA-Z0-9_]" [account-id]
    (GET "/show" _ (account/show account-id))))

(def access-rules
  {:rules [:pattern #"^/account/.*$"
           :handler authenticated-user?]})
```

Say, then, that a request is made to `"/account/12345/show"`. The problem is that the request will have a `:path-info` value of `"/show"` and a `:uri` value of `"/account/12345/show"`. Since the compiled matcher uses `:path-info` over `:uri` if it exists, the above access-rule will not match. But, it doesn't make terribly much sense to put an access rule on just `"/show"`. After all, it's every URI with `"/account/"` at the start that needs protecting, not URIs with `"/show"` at the end.

**Comment by rwilson** [comment]
Edited to remove incorrect statement that this was inconsistent with clout. Looking at the source for clout, it appears it does the exact same thing, allowing the `:path-info` to trump the `:uri` in pattern matching.

That means that given the above example, `{:uri "/account/*" ...}` also fails to match `"/account/12345/show"`.

**Comment by rwilson** [comment]
Did a little more digging, the root cause seems to be related to how `:path-info` is set, specifically when using Compojure's `(context... )` fn. 

For example, with this change to the route definition, both the `:uri` and `:pattern` matchers work as expected.

``` clojure
(defroutes
  (GET "/account/:account-id[a-zA-Z0-9_]/show" [account-id] (account/show account-id)))
```

I suppose that clout uses the `:path-info` for matching, _specifically because of_ `(context ...)`. Within a `(context ...)`, the path-info allows matching of partial uris, e.g. just `"/show"`.

**Comment by rwilson** [comment]
Final point, this also only occurs when using Compojure's `wrap-routes` method, to apply middleware after a route has been matched, which is a useful when the full app routes are a compound set of route groups, each with different middleware.

e.g.

``` clojure
(defroutes site-routes
  (GET "/something" _ #'some-handler))

(defroutes api-routes
  (context "/api"
    (GET "/some/resource" _ #'some-api-handler)))

(def all-routes
  (routes
    (-> site-routes
        (wrap-routes ring-defaults/wrap-defaults ring-defaults/site-defaults)
        (wrap-routes wrap-site-foo))
    (-> api-routes
        (wrap-routes ring-defaults/wrap-defaults ring-defaults/api-defaults)
        (wrap-routes wrap-api-bar))))

(defn app []
  (-> all-routes
      wrap-foo-around-all-routes
      wrap-bar-around-all-routes))
```

**Comment by niwinz** [comment]
Hmm, Clout, on its internals has that behavior:  https://github.com/weavejester/clout/blob/master/src/clout/core.clj#L35  and for work in a consistent way the regexp matching extracts the uri in the same way as clout.

But you are right, seems that this approach seems broken with `wrap-routes` of compojure. This can be two possible things: compojure uses incorrectly path-info or clout (and buddy) uses it wrong...

As additional thing, I haven't seen nothing about `:path-info` on the ring specification. So maybe the possible solution can be simply normalize everything to use only `:uri`?

**Comment by rwilson** [comment]
After looking at compojure, I'm fairly certain that it uses path-info for matching to make it easier to match paths within a context. For example:

``` clojure
(context "/foo"
  (GET "/bar" _ (handle-bar)))
```

An incoming request will have a URI of `"/foo/bar"`, but since the route defines only `"/bar"`, compojure has two choices, either:
1. pre-compile the routes to concatenate the context with the path, so that the route can match the full URI, or
2. treat "context" like the servlet spec concept of a "servlet context", in which case the incoming request will look like `{:context "/foo" :path-info "/bar" :uri "/foo/bar:"}`, and match routes against the path-info, so that it's all relative to the context.

From my reading, compojure takes the latter approach. And that's fine, I don't really see any problem with that.

So, getting to buddy-auth, I think the simplest approach would be to leave the `:uri` matcher as is (delegate to clout) but for the `:pattern` matcher, match against the full URI, rather than the path-info. The idea being that buddy-auth isn't operating within the concept of compojure's `(context ...)` a la a servlet-context, and therefore doesn't have a strong reason to match relative to a context vs absolute.

I created PR #29 with this small change. I think it should be fairly non-breaking, because in cases that weren't using context previously, it would already be matching the full URI.

**Comment by niwinz** [comment]
Sounds ok for me! I have merged the PR. I'll try to release a new version today.

**Comment by rwilson** [comment]
Looks like this didn't make it into the 0.6.1 release (at least, it's not in the tagged 0.6.1 codebase). How about a 0.6.2?

**Comment by niwinz** [comment]
I'll try release it today or tomorrow. Thanks for notice me about it.

**Comment by niwinz** [comment]
Now 0.6.2 is released.
