### ISSUE TITLE
Add buddy-auth to jwt.io

### ISSUE THREAD

**Issue by johnwalker** [funcool/buddy-auth#30]
Buddy-auth should be added to jwt, to help advertise and show what is supported from the spec.

http://jwt.io/

**Comment by niwinz** [comment]
Sorry for my late response. Thanks for the suggestion.

**Comment by niwinz** [comment]
Already done: https://github.com/jsonwebtoken/jsonwebtoken.github.io/pull/87

**Comment by johnwalker** [comment]
Nice!

**Comment by niwinz** [comment]
Done

**Comment by johnwalker** [comment]
Awesome, thanks!
