### ISSUE TITLE
NullPointerException marked

### ISSUE THREAD

**Issue by masas** [funcool/buddy-auth#36]
java.lang.NullPointerException: null
    at buddy.auth.middleware$wrap_authorization$fn__14021.invoke(middleware.clj:81) ~[classes/:na]

commit 32d3b70  "Remove slingshot usage" 
Missing throw argument
81 -            (throw+)))))))
83 +            (throw))))))) 

I guess avobe changes "(throw e)" ?

**Comment by niwinz** [comment]
Thanks for report it! I will fix it as soon as possible!

**Comment by niwinz** [comment]
Should be fixed in the last version (`buddy-auth==0.7.1` or `buddy==0.7.2`)

**Comment by spiffytech** [comment]
Confirmed fixed in buddy-auth 0.7.1, thanks!
