### ISSUE TITLE
ClassNotFoundException: org.bouncycastle.crypto.digests.Blake2bDigest - when upgrading from 0.7.1

### ISSUE THREAD

**Issue by NoamB** [funcool/buddy-auth#37]
Upgraded from 0.7.1 to 0.8.1.
Running tests - Fail with above exception.

I did not see any docs regarding upgrade instructions. Maybe I missed it?

Thanks.

**Comment by niwinz** [comment]
can you paste the output of the `lein deps :tree`? This is very strange.

**Comment by NoamB** [comment]
Thanks for the pointer...

changing: [pandect "0.5.4"]
to: [pandect "0.5.4" :exclusions [org.bouncycastle/bcprov-jdk15on]]

Solved the problem!

**Comment by niwinz** [comment]
Nice!
