### ISSUE TITLE
How do i invalidate a issued jws token before expiry.

### ISSUE THREAD

**Issue by sreekanthb** [funcool/buddy-auth#40]
Sorry,
I am not able to any documentation to invalidate the issued token, is there any method do that.
If i completely depend on my jws token, how do i signout the user.

**Comment by rundis** [comment]
You can't. You need to handle that by yourself in your app( you could always store tracing info about issued tokens in a db and check regularily using something like refresh tokens),. the token is self contained. The whole point of "stateless" auth really. Think of issued tokens as sent mails. You can't really take them back :) hey they can be stored in a users browsers cookie or on disk or whatever. 

Short story is. This is not a bug or missing feature in buddy imho.

**Comment by niwinz** [comment]
As @rundis says, that is not part of the jwt and how jwt works. 

In my personal experience, when I need invalidate tokens, I found me using a little hash 8 bytes (approx) hash/token/whatevername together with the user id. If I want invalidate the user tokens I just change the token on the user (in the database) and previously generated toke becomes invalid :D 

It there are a lot of different solutions, all depends on the specific behavior that you needs.
If JWT does not match you needs and more stateful approach, a token backend exists for that ;)

**Comment by sreekanthb** [comment]
Thanks @rundis @niwinz. I get it now.
