### ISSUE TITLE
Full examples

### ISSUE THREAD

**Issue by benjiqq** [funcool/buddy-auth#43]
Hi,

I extended the example with dependencies here, should these kinds of full examples be included? I can rebase to current version. Perhaps should go into a separate repository and linked in a wiki or doc.

https://github.com/funcool/buddy-auth/tree/118fe135881ce52dfffe21d73df4fec664c987d4/examples/session

See also this implementation of token based security with buddy:

http://rundis.github.io/blog/2015/buddy_auth_part1.html

Another example:
https://adambard.com/blog/clojure-auth-with-buddy/

**Comment by niwinz** [comment]
Hi @benjyz .

First of all, thank for your efforts. 

I'm not clearly understand this issue. Are you suggesting improve the current session example with your code? If this is the case, please do it, the PR is welcome. 

That dependencies that you are mentionening are strictly necessary? I like maintain the examples simple and less opinionated, just doing its purpose.

**Comment by benjiqq** [comment]
Hi @niwinz,

thanks, I didn't realise the examples work out of the box with lein profile, so PR is not necessary.
