### ISSUE TITLE
Authorization questions

### ISSUE THREAD

**Issue by DonDebonair** [funcool/buddy-auth#47]
**What does `wrap-authorization` do?**

When I have this handler for an access rule:

```
(defn authenticated-user
  [request]
  (if (authenticated? request)
    true
    (error "Only authenticated users are allowed")))
```

it seems that having `wrap-access-rules` and `wrap-authentication` is enough. What is the use-case for the `wrap-authorization` middleware?

**Why does `error` return a status 400 here?**

I'd assume that the `wrap-authorization` middleware would check if `authenticated?` is `true`, and if not, return the string I supplied with `error` together with status code `401`, and if it is `true`, return the string I supplied with status code `403`. Am I wrong in expecting this behaviour? Because currently, using `error` will result in status code `400`.

edit: I found out that, if I _do add_ the `wrap-authorization` middleware, and have my access-rule handler return `false` instead of `error`, the status codes are as expected: `401` when not `authenticated?`, `403` otherwise. This is nice and all, but that means I cannot simply override the error message by using `error` (because then I end up with `400`)

**Comment by DonDebonair** [comment]
Another question: What is the difference between having the access-rule handler return an error, and the `:on-error` function?

**Comment by niwinz** [comment]
`wrap-authorization` is a general purpose exception based authorization system. In majority of use cases, if you are using access rules, you don't need it. It just catch specific exceptions and handles them for return proper response. In fact, you can provide a user defined handler to the backend for that purpose.

The access rules by default raises the specific exception with the error found on evaluating the rule handlers. That exception is captured by `wrap-authorization` middleware. But if you don't like the approach, you can override it passing `:on-error` parameter with your own unauthorized handler.
