### ISSUE TITLE
Usage of buddy.auth.http/-get-header

### ISSUE THREAD

**Issue by iperdomo** [funcool/buddy-auth#49]
Hi, 
More than an actual problem is an implementation detail question/observation. According to the description, `buddy-auth` is:

> Authentication and Authorization facilities for ring and ring based web applications

This means the request and response should meet the Ring [SPEC](https://github.com/ring-clojure/ring/blob/1.4.0/SPEC). If you check the `:headers` of the _Request Map_, you'll find that the keys of the map, must be _downcased_, which lead us to get a particular value with a simple key lookup, e.g. `(get-in req [:headers "authorization"])`

```
:headers
  (Required, IPersistentMap)
  A Clojure map of downcased header name Strings to corresponding header value 
  Strings.
```

The current implementation of header lookup is a case-insensitve search through the map keys using `buddy.auth.http/-get-header`. Any thoughts on why is like this?

**Comment by niwinz** [comment]
buddy-auth is mainly build to be used for ring based applications, but it has some internal abstractions that makes it useful for use in with other similar abstractions. As far as I know, buddy-auth is also used together with pedestal.

**Comment by iperdomo** [comment]
@niwinz thanks for the reply

**Comment by iperdomo** [comment]
Not sure if i checked correctly, but it seems that pedestal is also using _downcase_ for header keys.
- https://github.com/pedestal/pedestal/blob/0.4.1/service/src/io/pedestal/http/impl/servlet_interceptor.clj#L166-L167
- https://github.com/pedestal/pedestal/blob/3483a6ce5067386e596577351e030c1e9fb8cdba/service/src/io/pedestal/http/request.clj#L16-L17
