### ISSUE TITLE
Wording, spelling, grammar

### ISSUE THREAD

**Issue by dijonkitchen** [funcool/buddy-auth#53]
There are a lot of wording, spelling, and grammar mistakes throughout the documentation. I understand English isn't everyone's first language; I just wanted to make a note of this for future contributors.

**Comment by niwinz** [comment]
I'm not clearly understand this issue, can you explain it a little bit more?

**Comment by dijonkitchen** [comment]
As a native english speaker I'm noticing some errors in the documentation with regards to spelling and grammar. It doesn't affect the code itself, as far as I've seen so far. Just wanted to make an issue so if others see this, they can improve the documentation to make it more readable.

**Comment by niwinz** [comment]
Of course, but having open a permanently issue just for that does not make sense for me.
If other see the documentation and see bugs/wordings/spellings/etc.. they can improve it.

**Comment by dijonkitchen** [comment]
I figure having an open issue will let others know there is something to fix. Once it is completed, the issue can be closed. 

It is your project though, so if you don't think it make sense, that's fine and you can close the issue.

**Comment by ghost** [comment]
>  If other see the documentation and see bugs/wordings/spellings/etc.. they can improve it. 

@dijonkitchen I'd encourage you to do the same when noticing spelling and grammar errors; you can edit the documentation from the GitHub interface directly.

**Comment by dijonkitchen** [comment]
Will do. And corrected.
