### ISSUE TITLE
Allow for successful authorization of requests that already contain :identity

### ISSUE THREAD

**Issue by robert-m-johnson** [funcool/buddy-auth#57]
For unit testing I've found it useful to simulate authenticated requests by simply adding an `:identity` entry to my test ring requests. This allows me to create tests for authorization that don't tie themselves to any particular authentication method.

However, buddy-auth doesn't allow this out of the box. The problem is that `middleware/authentication-request` will in effect `(assoc :identity nil)` to any request that doesn't match a particular authentication backend, overwriting any existing value of `:identity`. To get around this, I've created my own authentication backend that will retrieve this value if it already exists in the request:

```
(def map-entry-backend
  (reify
    buddy.auth.protocols/IAuthentication
    (-parse [_ request]
      (:identity request))
    (-authenticate [_ request data]
      data)))
```

Other users may find this functionality handy. It may be good to build in this functionality by either
1. Changing `middleware/authentication-request` to respect any existing values of `:identity`
2. Providing `map-entry-backend` as a build in back-end (possibly with a better name)

I guess the main issue is any security risk - I'm assuming that it is not possible for any ring handler to insert an identity entry itself, but I don't know enough about ring to say for sure. If this is an issue, then option 2 might still be worthwhile provided that the documentation adequately warns not to use it in production.

**Comment by niwinz** [comment]
I like the idea but I can't address it right now (I'm on my weeding)
