### ISSUE TITLE
Default token name for JWS should be Bearer?

### ISSUE THREAD

**Issue by ustun** [funcool/buddy-auth#60]
Just a nitpick, but from what I have seen on other sources, the default token name for JWS usually seems to be Bearer as opposed to Token. Should that be changed? One other advantage is that it might be easier to differentiate bt. normal token-based vs jwt based requests.

**Comment by niwinz** [comment]
Bearer is used for OAuth, and jwt is not directly related to the oauth. This is because Token is used.

**Comment by ustun** [comment]
OK, I guess we can close this then.
