### ISSUE TITLE
0.4.0 bump introduces a dependency on cljs for clj applications

### ISSUE THREAD

**Issue by rbxbx** [funcool/buddy-auth#7]
Due to how cljs is required in cuerda, any project using buddy-auth will rely on cljs.

https://github.com/funcool/cuerdas/blob/master/project.clj#L9

Perhaps referencing how `test.check` includes its cljs dependencies will be transferrable here, unsure https://github.com/clojure/test.check/commit/78d7df89a5c4c9b7a7b4fc2083bf1a59474a76dd

Not a major issue, but probably undesirable.

Thanks for your work on buddy et al!

**Comment by niwinz** [comment]
Thanks to you for report it. You are right, and I will fix it ;)

**Comment by niwinz** [comment]
Now fixed in 0.4.1 ;) thanks

**Comment by rbxbx** [comment]
Thanks @niwibe !
