### ISSUE TITLE
Support async handlers

### ISSUE THREAD

**Issue by mping** [funcool/buddy-auth#77]
Hi, any plan to support async handlers? https://github.com/ring-clojure/ring/wiki/Concepts#handlers

Should be a matter of implementing middlewares with 3-arity instead of 1-arity.

**Comment by niwinz** [comment]
Yes they are in the plan, but i dont know a proper ETA for them. Obviously, if you have time, PR is welcome.

**Comment by mping** [comment]
@niwinz Sure, I can take a look and do a PR. Thanks

**Comment by mping** [comment]
@niwinz I can either use a function that receives the handler, or a macro:

1. Convert all `(fn [request] ...)` calls into `(fnmult (fn [request] ...))` where `fnmult` receves a 1-aritiy handler and returns a multiple (1- and 3-) arity handler

2. Use a macro, changing all anonymous function declarations `(fn [request]` to `(fnmult [request] ...)` 

Do you have any preference?

**Comment by niwinz** [comment]
As your election, the one which seems more clear to understand and easy modify and extend for someone that have not writed that code.

**Comment by mping** [comment]
:+1:  merged by https://github.com/funcool/buddy-auth/pull/78 great job!
