### ISSUE TITLE
Regarding fn->multi macro

### ISSUE THREAD

**Issue by burhanloey** [funcool/buddy-auth#79]
Hi,

Love this library.

I took a look at `fn->multi` macro, and I don't think just wrapping `respond` function around the body will make it able to handle async request.

Take `wrap-authorization` middleware for example. Even when you wrap `respond` around it, you still only pass 1 argument (`request`) to the handler. For Ring handler that supports both sync and async, yes it will work, but that only means that it will always choose the sync implementation. For Ring handler that only supports async, it will just throw error saying not enough arguments.

So I tried to implement some buddy middlewares for async handlers and [this is how I make them work](https://gist.github.com/burhanloey/205e27b1b91dcd7c04b4c6ae06ad230f).

Also, I noticed there is no tests for async handler. There is only test for the macro.

**Comment by burhanloey** [comment]
Can I work on this issue?

I already got `wrap-access-rules` working including full test suite [here](https://github.com/burhanloey/buddy-auth/tree/async).

**Comment by niwinz** [comment]
Of course :D

**Comment by burhanloey** [comment]
I'm almost done. Should I remove `fn->multi` macro? I really can't find a way to put a macro since all middlewares are different from each other.

**Comment by niwinz** [comment]
Well done!

**Comment by burhanloey** [comment]
Thank you.
